# Generated by Django 4.2.2 on 2025-06-21 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=255, null=True)),
                ('tnm_staging', models.CharField(blank=True, max_length=255, null=True)),
                ('disease_stage', models.CharField(blank=True, max_length=255, null=True)),
                ('clinical_group', models.CharField(blank=True, max_length=255, null=True)),
                ('treatment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('treatment_phase', models.CharField(blank=True, max_length=255, null=True)),
                ('histology_number', models.CharField(blank=True, max_length=255, null=True)),
                ('histology_date', models.DateField(blank=True, null=True)),
                ('histology_description', models.TextField(blank=True, null=True)),
                ('ct_simulation_date', models.DateField(blank=True, null=True)),
                ('treatment_start_date', models.DateField(blank=True, null=True)),
                ('total_fractions', models.IntegerField(blank=True, null=True)),
                ('stage_description', models.CharField(blank=True, max_length=255, null=True)),
                ('current_fraction', models.IntegerField(blank=True, null=True)),
                ('missed_days', models.IntegerField(blank=True, null=True)),
                ('received_dose', models.FloatField(blank=True, null=True)),
                ('prior_radiation', models.CharField(blank=True, max_length=255, null=True)),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('inpatient_status', models.CharField(blank=True, max_length=255, null=True)),
                ('current_stage', models.CharField(blank=True, max_length=255, null=True)),
                ('treatment_goal', models.CharField(blank=True, max_length=255, null=True)),
                ('irradiation_zone', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('dose_per_fraction', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_blood_test_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='MedicalIncapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mvt_number', models.CharField(blank=True, max_length=19, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('no_employment_relation', models.BooleanField(blank=True, null=True)),
                ('no_employment_relation_text', models.CharField(blank=True, max_length=100, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patients.patient')),
            ],
            options={
                'db_table': 'medical_incapacity',
            },
        ),
        migrations.CreateModel(
            name='FractionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dose', models.FloatField()),
                ('delivered', models.BooleanField(blank=True, null=True)),
                ('confirmed_by_doctor', models.BooleanField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patients.patient')),
            ],
            options={
                'db_table': 'fraction_history',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('approved', models.BooleanField()),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(blank=True, db_column='doctor_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', related_query_name='user', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', related_query_name='user', to='auth.permission')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
