# Generated by Django 4.2.2 on 2025-06-21 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fractionhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fractions', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='medicalincapacity',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='medical_incapacities', to='patients.patient'),
        ),
    ]
