# Generated by Django 4.2.2 on 2025-06-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_fractionhistory_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ward_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='inpatient_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
