# Generated by Django 5.2.3 on 2025-06-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_ward_number_alter_patient_inpatient_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='current_fraction',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='current_stage',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='missed_days',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='stage_description',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='treatment_goal',
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Дата народження', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='clinical_group',
            field=models.CharField(blank=True, help_text='Клінічна група (текст)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ct_simulation_date',
            field=models.DateField(blank=True, help_text='Дата КТ-симуляції', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnosis',
            field=models.CharField(blank=True, help_text='Діагноз', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='discharge_date',
            field=models.DateField(blank=True, help_text='Дата виписки', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disease_stage',
            field=models.CharField(blank=True, help_text='Стадія захворювання (текст)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dose_per_fraction',
            field=models.FloatField(blank=True, help_text='РОД (Гр)', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(blank=True, help_text="Ім'я", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('Ч', 'Чоловіча'), ('Ж', 'Жіноча')], help_text='Стать', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='histology_date',
            field=models.DateField(blank=True, help_text='Дата гістології', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='histology_description',
            field=models.TextField(blank=True, help_text='Опис гістології', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='histology_number',
            field=models.CharField(blank=True, help_text='Номер гістології', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='inpatient_status',
            field=models.CharField(blank=True, help_text='Статус госпіталізації', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='irradiation_zone',
            field=models.CharField(blank=True, help_text='Зона опромінення', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_blood_test_date',
            field=models.DateField(blank=True, help_text='Дата останнього аналізу крові', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, help_text='Прізвище', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(blank=True, help_text='По батькові', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True, help_text='Примітки', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prior_radiation',
            field=models.CharField(blank=True, help_text='Попереднє опромінення', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='received_dose',
            field=models.FloatField(blank=True, help_text='СОД (Гр)', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tnm_staging',
            field=models.CharField(blank=True, help_text='Стадіювання за TNM', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='total_fractions',
            field=models.IntegerField(blank=True, help_text='Загальна кількість фракцій', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='treatment_phase',
            field=models.CharField(blank=True, help_text='Фаза лікування', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='treatment_start_date',
            field=models.DateField(blank=True, help_text='Дата початку лікування', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='treatment_type',
            field=models.CharField(blank=True, help_text='Тип лікування', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ward_number',
            field=models.IntegerField(blank=True, help_text='Номер палати', null=True),
        ),
    ]
