# Generated by Django 5.2.3 on 2025-07-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_patient_current_fraction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fractionhistory',
            name='is_missed',
            field=models.BooleanField(default=False, help_text='Чи пропущена фракція'),
        ),
        migrations.AddField(
            model_name='fractionhistory',
            name='is_postponed',
            field=models.BooleanField(default=False, help_text='Чи відкладена фракція'),
        ),
        migrations.AddField(
            model_name='fractionhistory',
            name='original_date',
            field=models.DateField(blank=True, help_text='Оригінальна дата фракції', null=True),
        ),
        migrations.AddField(
            model_name='fractionhistory',
            name='reason',
            field=models.CharField(blank=True, help_text='Причина зміни дати', max_length=255, null=True),
        ),
    ]
