# Generated by Django 5.2.3 on 2025-12-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0005_fractionhistory_is_missed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="ambulatory_card_id",
            field=models.CharField(
                blank=True,
                help_text="ID амбулаторної картки (наприклад: 228435/2025 або 2025-9246582)",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="ID амбулаторної картки",
            ),
        ),
    ]
