# Generated by Django 5.2.14 on 2026-05-21 07:41

from django.db import migrations, models

def migrate_fraction_statuses(apps, schema_editor):
    FractionHistory = apps.get_model('patients', 'FractionHistory')
    for fraction in FractionHistory.objects.all():
        if fraction.delivered or fraction.confirmed_by_doctor:
            fraction.status = 'delivered'
        elif fraction.is_missed:
            fraction.status = 'missed'
        else:
            fraction.status = 'scheduled'
        fraction.save()

def reverse_fraction_statuses(apps, schema_editor):
    FractionHistory = apps.get_model('patients', 'FractionHistory')
    for fraction in FractionHistory.objects.all():
        if fraction.status == 'delivered':
            fraction.delivered = True
            fraction.confirmed_by_doctor = True
            fraction.is_missed = False
        elif fraction.status == 'missed':
            fraction.delivered = False
            fraction.confirmed_by_doctor = False
            fraction.is_missed = True
        else:
            fraction.delivered = False
            fraction.confirmed_by_doctor = False
            fraction.is_missed = False
        fraction.save()

class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_add_ambulatory_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fractionhistory',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланована'), ('delivered', 'Отримана'), ('missed', 'Пропущена')], default='scheduled', help_text='Статус фракції', max_length=20),
        ),
        migrations.RunPython(migrate_fraction_statuses, reverse_fraction_statuses),
    ]
