# Generated by Django 5.2.14 on 2026-05-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_fractionhistory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fractionhistory',
            name='confirmed_by_doctor',
        ),
        migrations.RemoveField(
            model_name='fractionhistory',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='fractionhistory',
            name='is_missed',
        ),
        migrations.RemoveField(
            model_name='fractionhistory',
            name='is_postponed',
        ),
    ]
