# Generated by Django 5.2.14 on 2026-05-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_remove_fractionhistory_confirmed_by_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bed_owner',
            field=models.CharField(default='Олег', help_text="Прізвище лікаря, чиє ліжко зайнято. Якщо 'Олег' — це власне ліжко.", max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospitalization_status',
            field=models.CharField(choices=[('outpatient', 'Амбулаторно'), ('inpatient', 'Стаціонар'), ('queue', 'У черзі')], default='outpatient', help_text='Статус госпіталізації', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Чи є пацієнт активним (не в архіві)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='planned_admission_date',
            field=models.DateField(blank=True, help_text='Планова дата госпіталізації', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Чоловіча'), ('F', 'Жіноча')], help_text='Стать', max_length=10, null=True),
        ),
    ]
