# Generated by Django 5.2.14 on 2026-05-22 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_migrate_patient_inpatient_and_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='inpatient_status',
        ),
    ]
