# Generated by Django 5.2 on 2026-05-26
from django.db import migrations

def heal_schedules(apps, schema_editor):
    from patients.models import Patient
    from patients.services import shift_patient_schedule
    
    # Run scheduling healing for all patients to fix any historical gaps/errors
    for patient in Patient.objects.all():
        shift_patient_schedule(patient)

class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_remove_patient_inpatient_status'),
    ]

    operations = [
        migrations.RunPython(heal_schedules),
    ]
