# Generated by Django 5.2.3 on 2026-07-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0012_heal_patient_schedules"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="has_radiomodification",
            field=models.BooleanField(
                default=False,
                help_text="Потребує радіомодифікації (щотижневий аналіз крові)",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="raw_diagnosis",
            field=models.TextField(
                blank=True, help_text="Оригінальний вставлений діагноз", null=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="bed_owner",
            field=models.CharField(
                blank=True,
                default="Олег",
                help_text="Прізвище лікаря, чиє ліжко зайнято. Якщо 'Олег' — це власне ліжко.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="hospitalization_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("outpatient", "Амбулаторно"),
                    ("inpatient", "Стаціонар"),
                    ("queue", "У черзі"),
                ],
                default="outpatient",
                help_text="Статус госпіталізації",
                max_length=20,
            ),
        ),
    ]
