# Generated by Django 5.2.3 on 2026-07-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "patients",
            "0013_patient_has_radiomodification_patient_raw_diagnosis_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="encrypted_confidential_notes",
            field=models.TextField(
                blank=True, help_text="Зашифровані конфіденційні примітки", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pin_code",
            field=models.CharField(
                blank=True, help_text="Хеш PIN-коду", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pin_failed_attempts",
            field=models.IntegerField(
                default=0, help_text="Кількість неуспішних спроб введення PIN-коду"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pin_lockout_until",
            field=models.DateTimeField(
                blank=True, help_text="Час блокування введення PIN-коду", null=True
            ),
        ),
    ]
