# Generated by Django 5.2.16 on 2026-07-13 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_patient_encrypted_confidential_notes_user_pin_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fractionhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fractions', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='medicalincapacity',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_incapacities', to='patients.patient'),
        ),
    ]
