# Generated by Django 5.2.16 on 2026-07-13 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_alter_fractionhistory_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAIDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Дата щоденникового запису')),
                ('fraction_number', models.IntegerField(blank=True, help_text='Номер фракції', null=True)),
                ('ecog_status', models.IntegerField(default=0, help_text='Статус ECOG (0-4)')),
                ('ctcae_grade', models.IntegerField(default=0, help_text='Ступінь токсичності CTCAE (0-4)')),
                ('clinical_state_notes', models.TextField(help_text="Скарги та опис об'єктивного стану на цю дату")),
                ('generated_text', models.TextField(help_text='Згенерований ШІ текст щоденника')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_diaries', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_ai_diary',
                'ordering': ['date', 'fraction_number'],
            },
        ),
        migrations.CreateModel(
            name='PatientAIDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_state_notes', models.TextField(blank=True, help_text='Загальні нотатки про стан пацієнта для ШІ', null=True)),
                ('initial_assessment', models.TextField(blank=True, help_text='Згенерований ШІ первинний огляд', null=True)),
                ('discharge_summary', models.TextField(blank=True, help_text='Згенеровані ШІ дані для виписки', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_documentation', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_ai_documentation',
            },
        ),
    ]
