# Generated by Django 5.2.16 on 2026-07-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_patientaidiary_patientaidocumentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientaidiary',
            name='diary_type',
            field=models.CharField(choices=[('admission', 'При поступленні'), ('weekly', 'Щотижневий'), ('discharge', 'Виписний')], default='weekly', help_text='Тип щоденникового запису', max_length=20),
        ),
    ]
