# Generated by Django 5.2.16 on 2026-07-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_patientaidiary_diary_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dose_per_fraction_raw',
            field=models.CharField(blank=True, help_text='Текстовий запис РОД (наприклад: 2.0 або 2.66/3.0)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='dose_per_fraction_secondary',
            field=models.FloatField(blank=True, help_text='Другорядна РОД (Гр) при SIB', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_sib',
            field=models.BooleanField(default=False, help_text='Чи застосовується симультанний буст (SIB)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='received_dose_secondary',
            field=models.FloatField(blank=True, help_text='Другорядна СОД (Гр) при SIB', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dose_per_fraction',
            field=models.FloatField(blank=True, help_text='Основна РОД (Гр)', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='received_dose',
            field=models.FloatField(blank=True, help_text='Основна СОД (Гр)', null=True),
        ),
    ]
