# Generated by Django 5.2.16 on 2026-08-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_patient_mis_discharged'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назва шаблону / протоколу', max_length=200)),
                ('irradiation_zone', models.CharField(blank=True, help_text='Зона опромінення', max_length=200, null=True)),
                ('treatment_type', models.CharField(blank=True, help_text='Тип лікування', max_length=100, null=True)),
                ('total_fractions', models.IntegerField(help_text='Загальна кількість фракцій')),
                ('dose_per_fraction_raw', models.CharField(help_text='РОД (Гр), наприклад 2.0 або 2.66/3.0', max_length=50)),
                ('has_radiomodification', models.BooleanField(default=False, help_text='Радіомодифікація (Так/Ні)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'treatment_protocols',
                'ordering': ['name'],
            },
        ),
    ]
