# Generated by Django 5.2.16 on 2026-09-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0021_seed_default_protocols'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fractionhistory',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланована'), ('delivered', 'Отримана'), ('unverified', 'Не верифіковано'), ('missed', 'Пропущена')], default='scheduled', help_text='Статус фракції', max_length=20),
        ),
    ]
