# Generated by Django 5.2.16 on 2026-09-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0022_alter_fractionhistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='diagnosis',
            field=models.TextField(blank=True, help_text='Діагноз', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prior_radiation',
            field=models.TextField(blank=True, help_text='Попереднє опромінення', null=True),
        ),
    ]
